"""Minimal HTML template helpers for Atlas.

f-strings + an explicit `escape()` helper. No Jinja, no PyYAML, no
runtime template language. We pay a small ergonomics cost (no
template inheritance) for zero external dependencies on the
generated output.

Every renderer here returns a complete HTML document. The
build_atlas orchestrator picks which renderer to call per node.
"""

from __future__ import annotations

import html
from textwrap import dedent


def escape(value: object) -> str:
    """HTML-escape a value, handling None and non-strings."""
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


_BASE_HEAD = dedent("""\
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>{title}</title>
      <link rel="stylesheet" href="{root}static/atlas.css">
    </head>
""")


_NAV = dedent("""\
    <nav class="atlas-nav">
      <a href="{root}index.html">Atlas</a>
      <a href="{root}index.html#adrs">ADRs</a>
      <a href="{root}index.html#skills">Skills</a>
      <a href="{root}index.html#trajectories">Trajectories</a>
    </nav>
""")


def page(*, title: str, root: str, body: str) -> str:
    """Wrap a body in the standard head + nav + footer chrome."""
    head = _BASE_HEAD.format(title=escape(title), root=root)
    nav = _NAV.format(root=root)
    footer = (
        '<footer class="atlas-footer">'
        'Generated by <code>make atlas</code> (ADR-0049). '
        'Do not hand-edit; the next build will overwrite.'
        '</footer>'
    )
    return f"{head}<body>{nav}<main>{body}</main>{footer}</body></html>\n"


def link(href: str, label: str) -> str:
    return f'<a href="{escape(href)}">{escape(label)}</a>'


def badge(kind: str, label: str, value: str = "") -> str:
    """Render an inline badge: <span class="badge badge-<kind>">label[:value]</span>"""
    text = f"{label}: {value}" if value else label
    return f'<span class="badge badge-{escape(kind)}">{escape(text)}</span>'


def section(heading: str, items: list[str], *, id_: str = "") -> str:
    rows = "\n".join(f'<li>{item}</li>' for item in items) or "<li><em>none</em></li>"
    open_tag = f'<section id="{escape(id_)}">' if id_ else "<section>"
    return f'{open_tag}<h2>{escape(heading)}</h2><ul>{rows}</ul></section>'
