"""Per-project content materialization (ADR-0028).

Owns the unified target/.agents/ canonical store + per-tool symlink
projections + generated managed-block files. Invoked from
scripts/playbook_update.py; does NOT extend the home Adapter Protocol
(which stays focused on per-tool home-dir installs).

install_mode semantics:
  pointer  -> only refresh target/AGENTS.md pointer (existing v0.4 behavior)
  symlink  -> target/.agents/skills/<n> is a symlink to playbook/skills/<cat>/<n>/
              every other canonical entry (rules, hooks, mcp, agents, commands,
              prompts) is also a symlink to the playbook source file
  copy     -> canonical entries are deep copies; target is independent of
              playbook upstream until re-materialized

Per-tool projections (target/.claude/, target/.codex/) are always symlinks
into target/.agents/, regardless of install_mode. Hand-edits to projections
do not survive a re-materialize; the canonical .agents/ store is the only
write surface a project author should touch.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from adapters._loader import PlaybookContent
from agents_md import AgentsMd

LOCKFILE_NAME = ".playbook-state.json"

# Each per-tool projection: (tool dir, sub key -> canonical sub key).
# Keep simple: tools that present .agents/<type>/ at their native paths get a
# directory symlink. Generated artifacts (Cursor hooks.json, Copilot
# single-file) live alongside the symlink projections and are handled
# separately because the content shape differs.
TOOL_DIRECTORY_PROJECTIONS: dict[str, dict[str, str]] = {
    ".claude": {
        "skills": "skills",
        "commands": "commands",
        "agents": "agents",
        "hooks": "hooks",
    },
    ".codex": {
        "skills": "skills",
        "prompts": "prompts",
    },
    # v0.6: Cursor project projection (per gap-analysis F5). The .cursor/
    # tree gets four directory symlinks into .agents/. .cursor/hooks.json
    # is generated separately by _generate_cursor_hooks_json, and the
    # .cursor/rules/<name>.mdc files (with Cursor frontmatter) are
    # generated by _generate_cursor_mdc.
    ".cursor": {
        "skills": "skills",
        "commands": "commands",
        "agents": "agents",
        "hooks": "hooks",
    },
}


@dataclass(frozen=True)
class MaterializationResult:
    """Outcome of a TargetMaterializer.materialize() call. Used for
    user-facing print summary + lockfile persistence."""

    entries: dict[str, dict]
    install_mode: str
    counts: dict[str, int]


class TargetMaterializer:
    """Materialize PlaybookContent into a target project per ADR-0028."""

    def __init__(
        self,
        target: Path,
        repo_root: Path,
        install_mode: str,
    ) -> None:
        self.target = target.resolve()
        self.repo_root = repo_root.resolve()
        self.install_mode = install_mode
        # Cache of prior-install owned destinations so the safety guard in
        # _write_directory only allows rebuild when we genuinely own the
        # path. Reads target/.playbook-state.json once at construction time;
        # subsequent calls operate against this snapshot. Resolved absolute
        # paths (post-target-resolve) for direct comparison with dest.
        self._prior_owned_abs: set[Path] = self._load_prior_owned_paths()

    def _load_prior_owned_paths(self) -> set[Path]:
        prior = read_lockfile(self.target)
        if not prior:
            return set()
        owned: set[Path] = set()
        for rel_or_abs, entry in (prior.get("entries", {}) or {}).items():
            if not isinstance(entry, dict):
                continue
            if entry.get("ownership") != "owned":
                continue
            p = Path(rel_or_abs)
            if not p.is_absolute():
                p = self.target / p
            owned.add(p.resolve())
        return owned

    def materialize(self, content: PlaybookContent) -> MaterializationResult:
        """Run the materialization pipeline and return the lockfile-ready
        entries dict. Caller is responsible for writing the lockfile to disk;
        keeping the side effect outside lets a test inspect intent without
        touching disk.
        """
        if self.install_mode == "pointer":
            return self._materialize_pointer()
        if self.install_mode not in ("symlink", "copy"):
            raise ValueError(
                f"unknown install_mode {self.install_mode!r}; "
                f"expected pointer|symlink|copy"
            )

        entries: dict[str, dict] = {}
        counts: dict[str, int] = {}

        agents_dir = self.target / ".agents"
        agents_dir.mkdir(parents=True, exist_ok=True)

        counts["skills"] = self._materialize_skills(content, agents_dir, entries)
        counts["rules"] = self._materialize_single_files(
            [(r.path, f"{r.name}.md") for r in content.rules],
            agents_dir / "rules",
            entries,
        )
        counts["hooks"] = self._materialize_single_files(
            [(h.path, f"{h.name}.sh") for h in content.hooks],
            agents_dir / "hooks",
            entries,
        )
        counts["mcp"] = self._materialize_single_files(
            [(m.path, f"{m.name}.json") for m in content.mcp_configs],
            agents_dir / "mcp",
            entries,
        )
        counts["agents"] = self._materialize_single_files(
            [(a.path, f"{a.name}.md") for a in content.agents],
            agents_dir / "agents",
            entries,
        )
        counts["commands"] = self._materialize_single_files(
            [(c.path, f"{c.name}.md") for c in content.commands],
            agents_dir / "commands",
            entries,
        )
        counts["prompts"] = self._materialize_single_files(
            [(p.path, f"{p.name}.md") for p in content.prompts],
            agents_dir / "prompts",
            entries,
        )

        counts["projections"] = self._project_tool_directories(entries)
        counts["cursor_hooks_json"] = self._generate_cursor_hooks_json(
            content.hooks, entries
        )
        counts["cursor_mdc"] = self._generate_cursor_mdc(content.rules, entries)
        counts["copilot_md"] = self._generate_copilot_instructions(
            content.rules, entries
        )
        counts["agents_md"] = self._generate_target_agents_md(content.rules, entries)

        return MaterializationResult(
            entries=entries,
            install_mode=self.install_mode,
            counts=counts,
        )

    # === Pointer mode ===

    def _key(self, path: Path) -> str:
        """Render a lockfile key for a target-rooted path.

        Per Codex P2 #5: lockfile keys are relative to self.target so the
        per-project state file is portable (the project can move on disk
        or get checked out at a different absolute path without breaking
        prune_orphans). Falls back to the absolute string only for paths
        outside the target tree, which should not happen for entries
        written by this materializer.
        """
        try:
            return str(path.relative_to(self.target))
        except ValueError:
            return str(path)

    def _materialize_pointer(self) -> MaterializationResult:
        """install_mode=pointer: only refresh target/AGENTS.md pointer.
        Mirrors the v0.4 playbook_update.py behavior."""
        agents_md_path = self.target / "AGENTS.md"
        entries: dict[str, dict] = {}
        if agents_md_path.exists():
            doc = AgentsMd.load(agents_md_path)
            refreshed = doc.with_refreshed_pointer(self.repo_root)
            if refreshed is not doc:
                refreshed.save_to(agents_md_path)
            bumped = refreshed.with_last_reviewed(date.today().isoformat())
            if bumped is not refreshed:
                bumped.save_to(agents_md_path)
            entries[self._key(agents_md_path)] = {
                "ownership": "managed",
                "kind": "pointer",
            }
        # v0.7 fix: when switching from
        # symlink/copy to pointer, the prior project-level Cursor /
        # Windsurf hooks.json files remain on disk with playbook hook
        # registrations because they're tracked as ownership=managed
        # and prune_orphans only handles ownership=owned. Strip those
        # registrations so Cursor / Windsurf don't try to fire dead
        # hook scripts after the pointer-mode switch.
        prior = read_lockfile(self.target)
        if prior and prior.get("install_mode") in ("symlink", "copy"):
            self._strip_managed_project_hooks_json()
        return MaterializationResult(
            entries=entries,
            install_mode="pointer",
            counts={"pointer": 1 if agents_md_path.exists() else 0},
        )

    def _strip_managed_project_hooks_json(self) -> None:
        """Remove playbook-owned entries from project-level hooks.json files.

        Triggered on pointer-mode switch from a prior symlink/copy install.
        Touches `<target>/.cursor/hooks.json` and `<target>/.windsurf/hooks.json`
        only; user-level configs are out of scope here (those are owned by
        the home-install path and live behind their own lockfile).
        """
        candidates = [
            (self.target / ".cursor" / "hooks.json", ".cursor/hooks/"),
            (self.target / ".windsurf" / "hooks.json", ".windsurf/hooks/"),
        ]
        for hooks_json, owned_dir_substring in candidates:
            if not hooks_json.is_file():
                continue
            try:
                doc = json.loads(hooks_json.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                continue
            hook_block = doc.get("hooks")
            if not isinstance(hook_block, dict):
                continue
            stripped = 0
            for event, event_entries in list(hook_block.items()):
                if not isinstance(event_entries, list):
                    continue
                before = len(event_entries)
                hook_block[event] = [
                    entry
                    for entry in event_entries
                    if not (
                        isinstance(entry, dict)
                        and isinstance(entry.get("command"), str)
                        and owned_dir_substring in entry["command"]
                    )
                ]
                stripped += before - len(hook_block[event])
            if stripped:
                hooks_json.write_text(
                    json.dumps(doc, indent=2) + "\n", encoding="utf-8"
                )

    # === Canonical writes ===

    def _materialize_skills(
        self,
        content: PlaybookContent,
        agents_dir: Path,
        entries: dict[str, dict],
    ) -> int:
        """Write each skill as a directory entry under .agents/skills/.

        symlink mode: skills/<n> is a symlink to <repo>/skills/<cat>/<n>/.
        copy mode: skills/<n> is a deep copy of the same directory.
        """
        skills_dir = agents_dir / "skills"
        skills_dir.mkdir(parents=True, exist_ok=True)
        for skill in content.skills:
            install_name = skill.install_name or skill.name
            dest = skills_dir / install_name
            source_dir = skill.path.parent
            self._write_directory(source_dir, dest)
            entries[self._key(dest)] = {
                "ownership": "owned",
                "kind": "skill",
                "source": _relative_to_or_abs(source_dir, self.repo_root),
            }
        return len(content.skills)

    def _materialize_single_files(
        self,
        items: list[tuple[Path, str]],
        dest_dir: Path,
        entries: dict[str, dict],
    ) -> int:
        """Write each (source, target_basename) pair into dest_dir.

        symlink mode: dest is a symlink to source. copy mode: dest is a
        regular file copy. Either way an entry is recorded so re-install can
        prune.
        """
        if not items:
            return 0
        dest_dir.mkdir(parents=True, exist_ok=True)
        for source, basename in items:
            dest = dest_dir / basename
            self._write_file(source, dest)
            entries[self._key(dest)] = {
                "ownership": "owned",
                "kind": "canonical",
                "source": _relative_to_or_abs(source, self.repo_root),
            }
        return len(items)

    # === Per-tool projections ===

    def _project_tool_directories(self, entries: dict[str, dict]) -> int:
        """Create per-tool symlinks pointing into .agents/.

        target/.claude/skills -> ../.agents/skills
        target/.claude/commands -> ../.agents/commands
        (etc., per TOOL_DIRECTORY_PROJECTIONS)

        Projection sources are mkdir'd before the symlink so the Windows
        copy fallback (which raises FileNotFoundError on a missing source)
        sees a real dir to copy. Empty projection categories (e.g.
        `.agents/prompts/` when no prompts ship) stay empty on disk;
        Cursor / Codex / Claude all tolerate empty projection dirs.
        """
        count = 0
        agents_dir = self.target / ".agents"
        for tool_dirname, sub_map in TOOL_DIRECTORY_PROJECTIONS.items():
            tool_dir = self.target / tool_dirname
            tool_dir.mkdir(parents=True, exist_ok=True)
            for sub_name, canonical_sub in sub_map.items():
                source_dir = agents_dir / canonical_sub
                source_dir.mkdir(parents=True, exist_ok=True)
                link_path = tool_dir / sub_name
                target_relative = Path("..") / ".agents" / canonical_sub
                self._refresh_symlink(link_path, target_relative)
                entries[self._key(link_path)] = {
                    "ownership": "owned",
                    "kind": "projection",
                    "target": str(target_relative),
                }
                count += 1
        return count

    def _generate_target_agents_md(
        self,
        rules: list,
        entries: dict[str, dict],
    ) -> int:
        """Generate target/AGENTS.md managed block from rules. Existing
        non-managed content outside the markers is preserved.
        """
        agents_md_path = self.target / "AGENTS.md"
        AgentsMd.load_or_empty(agents_md_path).with_managed_rules(
            rules, label="target-materializer"
        ).save_to(agents_md_path)
        entries[self._key(agents_md_path)] = {
            "ownership": "managed",
            "kind": "agents_md",
        }
        return 1

    def _generate_cursor_hooks_json(
        self,
        hooks: list,
        entries: dict[str, dict],
    ) -> int:
        """Generate .cursor/hooks.json from content.hooks (per ADR-0034).

        Cursor expects camelCase events and a flat {command, matcher, timeout}
        shape; the cursor wrapper convention (PLAYBOOK-HOOK-CURSOR-WRAPPER)
        means the wrapper script is what's registered, and the cursor-only
        flag (PLAYBOOK-HOOK-CURSOR-ONLY) means cursor wrappers register only
        for cursor while being skipped by other adapters.

        Path semantics: commands use ".cursor/hooks/<name>.sh" relative to
        the project root, matching Cursor's documented project-level path
        contract. Cursor resolves these relative paths against the project
        root at runtime.

        User-authored entries in an existing .cursor/hooks.json are
        preserved across re-materializations: only entries whose command
        path matches a playbook-installed hook are surgically removed
        before fresh registrations append. The reconciliation here is
        idempotent on the same hook set (re-runs produce byte-identical
        output) and handles profile narrows (dropped hooks vanish).
        """
        cursor_dir = self.target / ".cursor"
        hooks_json = cursor_dir / "hooks.json"
        if not hooks and not hooks_json.exists():
            return 0

        cursor_dir.mkdir(parents=True, exist_ok=True)

        existing: dict = {"version": 1, "hooks": {}}
        if hooks_json.exists() and not hooks_json.is_symlink():
            try:
                existing = json.loads(hooks_json.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                existing = {"version": 1, "hooks": {}}
        existing.setdefault("version", 1)
        hook_block = existing.setdefault("hooks", {})

        # v0.6 (Codex review P2): strip every entry whose command points
        # into .cursor/hooks/ (regardless of whether it's in the new
        # profile). This handles profile narrows: dropped hooks leave
        # NO entry in hook_block. Without this, a narrowed profile would
        # keep stale registrations referencing absent hook scripts, and
        # Cursor would silently fail every fire of the missing hook.
        for event_entries in hook_block.values():
            if not isinstance(event_entries, list):
                continue
            event_entries[:] = [
                e
                for e in event_entries
                if not (
                    isinstance(e, dict)
                    and isinstance(e.get("command"), str)
                    and _cursor_command_points_to_project_hook(e["command"])
                )
            ]

        registered = 0
        if hooks:
            from hook_registration import (
                cursor_shaped_entry,
                is_cursor_only,
                is_hook_for_adapter,
                resolve_cursor_wrapper,
            )

            # v0.8 (ADR-0037): drop hooks pinned to a different adapter via
            # PLAYBOOK-HOOK-ADAPTERS (e.g., anchored-fs claude-shape hooks).
            # The target materializer's cursor projection should match what
            # the cursor adapter would register at global scope.
            hooks = [h for h in hooks if is_hook_for_adapter(h, "cursor")]

            for hook in hooks:
                # The cursor wrapper itself registers normally; the wrapped core
                # is copied (via the projection symlink) but not registered.
                if resolve_cursor_wrapper(hook) is not None and not is_cursor_only(
                    hook
                ):
                    continue
                command_path = f".cursor/hooks/{hook.name}.sh"
                # v0.6 (Codex review P2): the materializer's canonical hook
                # source is .agents/hooks/<name>.sh, which is a symlink chain
                # to the playbook's hooks/ tree. Project-level Cursor needs
                # those scripts executable. Wrap the command in `bash` so
                # missing +x mode on the canonical source doesn't surface as
                # a Cursor permission-denied error.
                event, entry = cursor_shaped_entry(hook, command_path)
                entry["command"] = f"bash {command_path}"
                hook_block.setdefault(event, []).append(entry)
                registered += 1

        hooks_json.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")
        entries[self._key(hooks_json)] = {
            "ownership": "managed",
            "kind": "cursor_hooks_json",
        }
        return registered

    def _generate_cursor_mdc(self, rules: list, entries: dict[str, dict]) -> int:
        """Generate .cursor/rules/<name>.mdc files from content.rules.

        Cursor reads rules from .cursor/rules/*.mdc with a YAML frontmatter
        header (description / alwaysApply / globs). Source rules live in
        skills/.../*.md without that frontmatter, so the materializer wraps
        each rule's body in the Cursor envelope. Output files are 'owned'
        in the lockfile: a later install with a narrower profile drops the
        ones that fell out.
        """
        if not rules:
            return 0
        rules_dir = self.target / ".cursor" / "rules"
        rules_dir.mkdir(parents=True, exist_ok=True)
        count = 0
        from adapters._loader import first_heading_or_default

        for rule in rules:
            mdc_path = rules_dir / f"{rule.name}.mdc"
            description = first_heading_or_default(
                rule.body, default="Auto-distributed rule from coding-agents-playbook"
            )
            frontmatter = (
                "---\n"
                f"description: {description}\n"
                "alwaysApply: true\n"
                'globs: "**/*"\n'
                "---\n\n"
            )
            mdc_path.write_text(frontmatter + rule.body, encoding="utf-8")
            entries[self._key(mdc_path)] = {
                "ownership": "owned",
                "kind": "cursor_mdc",
                "source": _relative_to_or_abs(rule.path, self.repo_root),
            }
            count += 1
        return count

    def _generate_copilot_instructions(
        self, rules: list, entries: dict[str, dict]
    ) -> int:
        """Generate .github/copilot-instructions.md from content.rules.

        GitHub Copilot reads repository-wide guidance from a single file
        with managed-block markers. Pre-existing hand-authored content
        outside the markers is preserved across re-materializations.
        Returns 1 if a file was written, 0 if no rules ship.
        """
        if not rules:
            return 0
        from adapters._loader import compose_agents_md, upsert_managed_block

        github_dir = self.target / ".github"
        github_dir.mkdir(parents=True, exist_ok=True)
        copilot_md = github_dir / "copilot-instructions.md"
        body = compose_agents_md(rules).rstrip()
        header = (
            "# Copilot Instructions\n\n"
            "Repository-wide guidance for GitHub Copilot. The block below is "
            "auto-managed by the coding-agents-playbook installer; content "
            "outside the markers is hand-authored and preserved across "
            "re-installs."
        )
        upsert_managed_block(copilot_md, body, header=header)
        entries[self._key(copilot_md)] = {
            "ownership": "managed",
            "kind": "copilot_md",
        }
        return 1

    # === Filesystem primitives ===

    def _write_directory(self, source: Path, dest: Path) -> None:
        """Materialize source directory at dest per install_mode.

        Per Codex P1 #2: the safety guard now consults the prior lockfile
        ownership cache, not just a path-prefix check. A real directory
        at dest is replaced only when prior_owned tracked it; otherwise
        we raise FileExistsError so unowned project-local content (e.g.
        a manually-created .agents/skills/<n>/ from a prior non-playbook
        setup) is never silently deleted.
        """
        dest_abs = dest.resolve() if dest.exists() or dest.is_symlink() else dest
        if dest.is_symlink():
            dest.unlink()
        elif dest.exists():
            if dest.is_dir():
                if dest_abs not in self._prior_owned_abs:
                    raise FileExistsError(
                        f"refusing to replace directory {dest}: the prior "
                        f"lockfile (target/.playbook-state.json) does not "
                        f"record this path as playbook-owned. Move the "
                        f"directory elsewhere before re-running, or delete "
                        f"the lockfile to start fresh."
                    )
                shutil.rmtree(dest)
            else:
                dest.unlink()
        if self.install_mode == "symlink":
            from adapters._loader import safe_symlink_or_copy

            safe_symlink_or_copy(dest, source.resolve(), target_is_directory=True)
        else:
            shutil.copytree(source, dest)

    def _write_file(self, source: Path, dest: Path) -> None:
        """Materialize source file at dest per install_mode.

        Per Codex adversarial review round-2 [high]: same ownership
        guard as _write_directory. A real (non-symlink) file at dest
        that the prior lockfile does NOT record as owned is project-
        local content; refuse to clobber. Symlinks are always playbook-
        owned (the only writer in this codebase is this method), so
        replacing them is safe.
        """
        dest_abs = dest.resolve() if dest.exists() or dest.is_symlink() else dest
        if dest.is_symlink():
            dest.unlink()
        elif dest.exists():
            if dest_abs not in self._prior_owned_abs:
                raise FileExistsError(
                    f"refusing to replace file {dest}: the prior lockfile "
                    f"(target/.playbook-state.json) does not record this "
                    f"path as playbook-owned. Move the file elsewhere "
                    f"before re-running, or delete the lockfile to start "
                    f"fresh."
                )
            dest.unlink()
        if self.install_mode == "symlink":
            from adapters._loader import safe_symlink_or_copy

            safe_symlink_or_copy(dest, source.resolve())
        else:
            shutil.copy2(source, dest)

    def _refresh_symlink(self, link_path: Path, target: Path) -> None:
        """Idempotently (re)create a symlink. Used for projections.

        Safety guard added in v0.5 (per adversarial review high-severity
        finding): never rmtree a real directory. If link_path is a regular
        directory or a real file that the playbook does not own, refuse to
        clobber it and raise FileExistsError so the user sees the conflict
        instead of losing project-local content.

        v0.7 Windows extension: on Windows without symlink privilege,
        safe_symlink_or_copy falls back to copy and the projection becomes
        a real directory. The prior_owned cache (read from .playbook-state.json
        at construction) records every owned path; if the existing dir is
        in that cache, it's our own copy from the previous install, so we
        rmtree + recreate rather than refuse. Unowned dirs still raise.
        """
        if link_path.is_symlink():
            link_path.unlink()
        elif link_path.exists():
            link_abs = link_path.resolve()
            if link_path.is_dir():
                if link_abs not in self._prior_owned_abs:
                    raise FileExistsError(
                        f"refusing to replace existing directory {link_path} "
                        f"with a playbook projection symlink. Move or delete it "
                        f"first; the playbook will not clobber project-local "
                        f"content. (TargetMaterializer projection safety guard, "
                        f"per ADR-0028 v0.5 finding.)"
                    )
                # Prior-owned (e.g. Windows fallback copy from a previous
                # install). Safe to rebuild from the new source.
                shutil.rmtree(link_path)
            else:
                link_path.unlink()
        from adapters._loader import safe_symlink_or_copy

        safe_symlink_or_copy(link_path, target, target_is_directory=True)


def _relative_to_or_abs(path: Path, base: Path) -> str:
    """Render path relative to base when possible, else return the absolute
    string. Used to keep lockfile entries short for in-repo sources while
    tolerating out-of-tree paths (e.g. test fixtures, future cross-repo
    content references).
    """
    try:
        return str(path.relative_to(base))
    except ValueError:
        return str(path.resolve())


# _first_heading_or_default moved to scripts/adapters/_writer.py as
# first_heading_or_default and re-exported via _loader so cursor.py /
# windsurf.py / target_materializer.py all share one implementation
# (v0.6 review-2 fixup).


def _cursor_command_points_to_project_hook(command: str) -> bool:
    """Return True for materializer-owned project hook commands.

    v0.6 first wrote bare `.cursor/hooks/<name>.sh` commands, then switched
    to `bash .cursor/hooks/<name>.sh` so executable-bit drift would not break
    Cursor. Both forms point at the playbook-managed project hook projection.
    """
    return command.startswith(".cursor/hooks/") or command.startswith(
        "bash .cursor/hooks/"
    )


def write_lockfile(target: Path, result: MaterializationResult) -> Path:
    """Write target/.playbook-state.json. Returns the path written.

    The lockfile is intentionally simple: a single mapping from string paths
    to entry dicts. Future v0.6 can add a managed_keys section similar to the
    home install's lockfile if the projection cleanup needs it; for v0.5 the
    set of entry paths is sufficient because every projection is owned by the
    playbook (no user-mixed entries to disambiguate).
    """
    lockfile_path = target / LOCKFILE_NAME
    payload = {
        "version": "0.5",
        "generated_at": date.today().isoformat(),
        "install_mode": result.install_mode,
        "entries": result.entries,
    }
    lockfile_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return lockfile_path


def read_lockfile(target: Path) -> dict | None:
    """Return the parsed lockfile or None if absent / unreadable."""
    lockfile_path = target / LOCKFILE_NAME
    if not lockfile_path.exists():
        return None
    try:
        return json.loads(lockfile_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def prune_orphans(target: Path, new_entries: dict[str, dict]) -> int:
    """Remove canonical + projection entries from the prior lockfile that
    no longer appear in the current materialization.

    Returns the count of paths actually removed. Symlinks are unlinked;
    regular files are deleted; directories are removed via rmtree only when
    they were recorded as 'owned'.

    Per Codex P2 #5: lockfile keys can be either relative (v0.5+) or
    absolute (v0.4 lockfiles). Relative keys resolve against the current
    target; absolute keys are honored as-is. The comparison against
    new_entries uses both shapes so a relocated project with absolute
    keys in its prior lockfile still gets cleaned up.
    """
    prior = read_lockfile(target)
    if not prior:
        return 0
    prior_entries = prior.get("entries", {}) or {}
    target = target.resolve()
    # Build a set of "new" keys in BOTH relative and absolute form so the
    # equality check works regardless of which shape either side uses.
    new_keys_normalized: set[str] = set()
    for key in new_entries.keys():
        new_keys_normalized.add(key)
        path = Path(key)
        if path.is_absolute():
            try:
                new_keys_normalized.add(str(path.relative_to(target)))
            except ValueError:
                pass
        else:
            new_keys_normalized.add(str((target / path).resolve()))

    removed = 0
    for path_str, entry in prior_entries.items():
        # Skip if this entry still belongs to the current materialization
        if path_str in new_keys_normalized:
            continue
        path = Path(path_str)
        if not path.is_absolute():
            path = target / path
        # Codex adversarial review round-2 [critical]: a corrupted /
        # malicious / cross-machine lockfile could carry paths outside
        # the target tree (absolute /etc/passwd, or relative ../../../).
        # The chokepoint guard: the path's PARENT must resolve to a
        # location under target. Resolving the parent (not the leaf)
        # defeats `..` traversal AND preserves intentional playbook
        # symlinks at the leaf (which resolve to playbook source files
        # outside target, by design of symlink mode).
        try:
            parent_real = path.parent.resolve(strict=False)
            parent_real.relative_to(target)
        except ValueError:
            continue
        final = parent_real / path.name
        if not (final.exists() or final.is_symlink()):
            continue
        ownership = (
            entry.get("ownership", "owned") if isinstance(entry, dict) else "owned"
        )
        if ownership != "owned":
            continue
        try:
            if final.is_symlink():
                final.unlink()
            elif final.is_dir():
                shutil.rmtree(final)
            else:
                final.unlink()
            removed += 1
        except OSError:
            continue
    return removed
